version: '3'

networks: 
  laravel:
    driver: bridger

services: 
  nginx:
    image: nginx:stable-alpine
    args:
      - NGINXUSER=${NGINXUSER:-www-data}
      - NGINXGROUP=${NGINXGROUP:-www-data}
    container_name: webserver
    ports:
      - "8088:80"
    volumes: 
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - php
      - mysql
    networks: 
      - laravel


  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    volumes: 
      - ./mysql:/var/lib/mysql
    environment: 
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: ${SERVICE_TAG}
      SERVICE_NAME: mysql
    networks: 
      - laravel
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    networks: 
      - laravel
